#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_SOURCE="${1:-}"
OUTPUT_FILE="${MOBILE_ENV_OUTPUT:-$REPO_ROOT/apps/mobile/.env}"

if [ -z "$ENV_SOURCE" ]; then
  if [ -f "$REPO_ROOT/.env.local" ]; then
    ENV_SOURCE="$REPO_ROOT/.env.local"
  elif [ -f "$REPO_ROOT/.env.oss.example" ]; then
    ENV_SOURCE="$REPO_ROOT/.env.oss.example"
  else
    echo "Error: create .env.local or keep .env.oss.example available before syncing mobile env."
    exit 1
  fi
elif [ "${ENV_SOURCE#/}" = "$ENV_SOURCE" ]; then
  ENV_SOURCE="$REPO_ROOT/$ENV_SOURCE"
fi

if [ ! -f "$ENV_SOURCE" ]; then
  echo "Error: mobile env source not found: $ENV_SOURCE"
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "$ENV_SOURCE"
set +a

if [ -z "${EXPO_PUBLIC_API_URL:-}" ]; then
  if [ -z "${NEXT_PUBLIC_APP_URL:-}" ]; then
    echo "Error: EXPO_PUBLIC_API_URL or NEXT_PUBLIC_APP_URL is required in $ENV_SOURCE."
    exit 1
  fi
  export EXPO_PUBLIC_API_URL="${NEXT_PUBLIC_APP_URL%/}/api"
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

tmp="$(mktemp)"
{
  echo "# Generated by scripts/sync-mobile-env.sh from ${ENV_SOURCE#$REPO_ROOT/}."
  echo "# Do not commit this file."
  env | awk -F= '/^EXPO_PUBLIC_/ { print }' | sort
} > "$tmp"
mv "$tmp" "$OUTPUT_FILE"

echo "Wrote $OUTPUT_FILE"
