'use client';

import { useState } from 'react';
import type { ReferenceData } from '@/types/reference';
import styles from './ReferenceList.module.css';

interface ReferenceListProps {
  references: ReferenceData[];
}

const TYPE_LABELS: Record<string, string> = {
  WEB: 'Web',
  PAPER: 'Paper',
  BOOK: 'Book',
  ARTICLE: 'Article',
  VIDEO: 'Video',
  REPORT: 'Report',
};

export function ReferenceList({ references }: ReferenceListProps) {
  const [expanded, setExpanded] = useState(references.length <= 10);

  if (references.length === 0) return null;

  const sorted = [...references].sort((a, b) => a.number - b.number);

  return (
    <section className={styles.root} aria-label="References">
      <button
        className={styles.header}
        onClick={() => setExpanded((prev) => !prev)}
        aria-expanded={expanded}
        type="button"
      >
        <h3 className={styles.heading}>
          References
          <span className={styles.count}>({references.length})</span>
        </h3>
        <svg
          className={`${styles.chevron} ${expanded ? styles.chevronOpen : ''}`}
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>

      {expanded && (
        <div className={styles.content}>
          <ol className={styles.list}>
            {sorted.map((ref) => (
              <li key={ref.id} className={styles.item} value={ref.number}>
                <div className={styles.refBody}>
                  <span className={styles.title}>{ref.title}</span>
                  {ref.authors.length > 0 && (
                    <span className={styles.authors}>
                      {ref.authors.join(', ')}
                    </span>
                  )}
                  <span className={styles.meta}>
                    {ref.year && <span>{ref.year}</span>}
                    {ref.publisher && (
                      <>
                        {ref.year && ' \u00B7 '}
                        <span>{ref.publisher}</span>
                      </>
                    )}
                    {' \u00B7 '}
                    <span className={styles.typeBadge}>
                      {TYPE_LABELS[ref.type] || ref.type}
                    </span>
                  </span>
                  {ref.url && (
                    <a
                      href={ref.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className={styles.link}
                    >
                      {ref.url}
                    </a>
                  )}
                  {ref.doi && (
                    <span className={styles.doi}>DOI: {ref.doi}</span>
                  )}
                </div>
              </li>
            ))}
          </ol>
          <p className={styles.disclaimer}>
            References were generated by AI. Please verify sources independently.
          </p>
        </div>
      )}
    </section>
  );
}
