const CHALLENGE_PHRASES = [
  'The quick brown fox jumps over the lazy sleeping dog near the river bank.',
  'She sells colorful seashells by the beautiful sandy seashore every morning.',
  'Peter Piper picked a peck of pickled peppers from the garden patch.',
  'How much wood would a busy woodchuck chuck if a woodchuck could chuck wood.',
  'The bright golden sun sets behind the tall purple mountains in the west.',
  'A journey of a thousand miles begins with just a single small step forward.',
  'Every great adventure starts with a moment of genuine curiosity and wonder.',
  'The gentle breeze carries the sweet fragrance of blooming wildflowers through the valley.',
  'Knowledge is the key that unlocks every door along the path to wisdom.',
  'Stars twinkle brightly in the velvet darkness of the midnight summer sky.',
  'Music fills the empty concert hall with waves of beautiful sound and emotion.',
  'The old lighthouse keeper watches the ships sail across the foggy harbor entrance.',
  'Fresh morning dew glistens on the emerald green leaves of the oak tree.',
  'Courage is not the absence of fear but the triumph over it each day.',
  'The winding mountain trail leads to a breathtaking view of the glacier lake.',
  'Creativity flows like a river finding its natural path through the landscape.',
  'The ancient library holds centuries of forgotten stories waiting to be discovered.',
  'Thunder rumbles across the open plains as dark storm clouds gather overhead.',
  'A warm cup of coffee makes even the coldest winter mornings feel better.',
  'The playful dolphins leap gracefully through the sparkling ocean waves at dawn.',
  'Beneath the cherry blossom trees the children dance and laugh with pure joy.',
  'The master craftsman shapes raw material into something beautiful and lasting with care.',
  'Autumn leaves paint the forest floor in shades of crimson gold and amber.',
  'The first snowfall of winter transforms the entire landscape into a wonderland.',
  'Innovation happens when preparation meets opportunity at the intersection of bold ideas.',
  'The moonlight reflects off the calm surface of the still mountain lake tonight.',
  'Patience and persistence are the foundations upon which great achievements are built.',
  'The rhythmic sound of ocean waves soothes the mind and calms the spirit.',
  'Bright colorful butterflies flutter between the fragrant roses in the garden pathway.',
  'The skilled musician plays melodies that touch the deepest corners of the heart.',
  'A single candle flame can illuminate the darkest room with its warm glow.',
  'The morning chorus of songbirds announces the arrival of a beautiful new spring.',
  'Great discoveries often begin with a simple question that challenges conventional thinking.',
  'The silver moonbeams dance across the rippling surface of the quiet forest pond.',
  'Kindness is a language that the deaf can hear and the blind can see.',
  'The majestic eagle soars high above the rugged canyon walls at sunrise.',
  'Fresh baked bread fills the cozy kitchen with an irresistible aroma of comfort.',
  'The traveling merchant tells fascinating tales from distant lands beyond the horizon.',
  'Sunlight streams through the stained glass windows creating rainbow patterns on the floor.',
  'The wise gardener knows that every season brings its own gifts and challenges.',
  'Crystal clear water cascades down the rocky cliff face into the pool below.',
  'The curious child explores the attic and discovers a trunk full of treasures.',
  'Gentle rain taps against the window pane as the fireplace crackles with warmth.',
  'The seasoned captain navigates through rough waters with calm confidence and steady hands.',
  'Purple wildflowers blanket the hillside creating a stunning display of natural beauty.',
  'The talented painter captures the essence of twilight in bold strokes of color.',
  'Laughter echoes through the hallways as old friends reunite after many long years.',
  'The northern lights shimmer and dance across the Arctic sky in green and violet.',
  'Every sunset is a reminder that endings can be just as beautiful as beginnings.',
  'The stone bridge arches gracefully over the babbling brook in the village square.',
];

export const CHALLENGE_EXPIRY_MS = 10 * 60 * 1000; // 10 minutes
export const MAX_CHALLENGE_ATTEMPTS = 3;

export function generateChallengePhrase(): string {
  return CHALLENGE_PHRASES[Math.floor(Math.random() * CHALLENGE_PHRASES.length)];
}
